# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build_Upload
  displayName: Build Lambda Zip Files
  jobs:
  - job: BuildJob
    pool:
      vmImage: ubuntu-latest
    steps:
    - bash: echo Zipping lambda directory
    # - bash: cd $(System.DefaultWorkingDirectory)/backend &&
    - script: ls
      workingDirectory: $(System.DefaultWorkingDirectory)/backend
      displayName: List contents of a folder
    # - task: ArchiveFiles@2
    #   inputs:
    #     rootFolderOrFile: '$(System.DefaultWorkingDirectory)/backend/'
    #     includeRootFolder: false
    #     archiveType: 'zip'
    #     archiveFile: 'rest-api.zip'
    #     replaceExistingArchive: true

    # - task: S3Upload@1
    #   inputs:
    #     awsCredentials: 'cicd_credential'
    #     regionName: 'eu-central-1'
    #     bucketName: 'sample-project-ka2-backend'
    #     sourceFolder: '$(Build.ArtifactStagingDirectory)/rest-api.zip'
    #     globExpressions: '**'
